server:
  session:
    timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
  port: 8000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/data/h2;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root

mybatis:
  mapper-locations: mybatis/**/**Mapper.xml
  type-aliases-package: com.dsz.**.model

